//@ui5-bundle com/myorg/stockscanner/Component-preload.js
sap.ui.require.preload({
	"com/myorg/stockscanner/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","com/myorg/stockscanner/model/models"],function(e,t,i){"use strict";return e.extend("com.myorg.stockscanner.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"com/myorg/stockscanner/controller/BaseController.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/core/routing/History","sap/ui/core/UIComponent","com/myorg/stockscanner/model/formatter"],function(e,t,o,n){"use strict";return e.extend("com.myorg.stockscanner.controller.BaseController",{formatter:n,getModel:function(e){return this.getView().getModel(e)},setModel:function(e,t){return this.getView().setModel(e,t)},getResourceBundle:function(){return this.getOwnerComponent().getModel("i18n").getResourceBundle()},navTo:function(e,t,o){this.getRouter().navTo(e,t,o)},getRouter:function(){return o.getRouterFor(this)},onNavBack:function(){var e=t.getInstance().getPreviousHash();if(e!==undefined){window.history.back()}else{this.getRouter().navTo("appHome",{},true)}}})});
},
	"com/myorg/stockscanner/controller/MainView.controller.js":function(){sap.ui.define(["com/myorg/stockscanner/controller/BaseController"],function(o){"use strict";return o.extend("com.myorg.stockscanner.controller.MainView",{onInit:function(){console.log("test");var o=new sap.ui.model.json.JSONModel;o.loadData("http://localhost:8081/0.0.0.0:4004/recommendations").then(()=>{this.getView().setModel(o,"recommendations")}).catch(o=>console.log(o))}})});
},
	"com/myorg/stockscanner/i18n/i18n.properties":'title=com.myorg.stockscanner\nappTitle=com.myorg.stockscanner\nappDescription=App Description\n',
	"com/myorg/stockscanner/i18n/i18n_en.properties":'title=com.myorg.stockscanner\nappTitle=com.myorg.stockscanner\nappDescription=App Description\n',
	"com/myorg/stockscanner/manifest.json":'{"_version":"1.21.0","sap.app":{"id":"com.myorg.stockscanner","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}"},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"rootView":{"viewName":"com.myorg.stockscanner.view.MainView","type":"XML","async":true,"id":"idAppControl"},"dependencies":{"minUI5Version":"1.60.0","libs":{"sap.ui.core":{},"sap.m":{},"sap.ui.layout":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.myorg.stockscanner.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","viewPath":"com.myorg.stockscanner.view","controlId":"idAppControl","controlAggregation":"pages","async":true},"routes":[{"name":"RouteMainView","pattern":"RouteMainView","target":["TargetMainView"]}],"targets":{"TargetMainView":{"viewType":"XML","viewLevel":1,"viewId":"idAppControl","viewName":"MainView"}}}}}',
	"com/myorg/stockscanner/model/formatter.js":function(){sap.ui.define([],function(){"use strict";return{}});
},
	"com/myorg/stockscanner/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"com/myorg/stockscanner/view/MainView.view.xml":' <mvc:View controllerName="com.myorg.stockscanner.controller.MainView"\n  displayBlock="true"\n  xmlns="sap.m"\n  xmlns:ui="sap.ui.table"\n  xmlns:mvc="sap.ui.core.mvc"><App id="idAppControl" ><pages><Page title="{i18n>title}"><content><ui:Table\n            rows="{recommendations>/}"\n            selectionMode="MultiToggle"\n            visibleRowCount="14"\n            ariaLabelledBy="title"><ui:columns><ui:Column width="11rem"><Label text="Company" /><ui:template><Text text="{recommendations>symbol}" wrapping="false" /></ui:template></ui:Column><ui:Column width="11rem"><Label text="buy" /><ui:template><Text text="{recommendations>buy}" wrapping="false" /></ui:template></ui:Column><ui:Column width="11rem"><Label text="hold" /><ui:template><Text text="{recommendations>hold}" wrapping="false" /></ui:template></ui:Column><ui:Column width="11rem"><Label text="sell" /><ui:template><Text text="{recommendations>sell}" wrapping="false" /></ui:template></ui:Column><ui:Column width="11rem"><Label text="period" /><ui:template><Text text="{recommendations>period}" wrapping="false" /></ui:template></ui:Column></ui:columns></ui:Table></content></Page></pages></App></mvc:View>'
});
